### ISSUE TITLE
can´t compile xCGUITTFont

### ISSUE THREAD

**Issue by JPRuehmann** [minetest/minetest#5018]
Hello
My make is terminating with the following error. What can I do?
```
[ 39%] Building CXX object src/cguittfont/CMakeFiles/cguittfont.dir/xCGUITTFont.cpp.o
In file included from /home/ruehmann/minetest/src/cguittfont/xCGUITTFont.h:7:0,
                 from /home/ruehmann/minetest/src/cguittfont/xCGUITTFont.cpp:4:
/home/ruehmann/minetest/src/cguittfont/CGUITTFont.h: In member function ‘bool irr::gui::CGUITTGlyphPage::createPageTexture(const u8&, const dimension2du&)’:
/home/ruehmann/minetest/src/cguittfont/CGUITTFont.h:129:50: error: ‘ETCF_ALLOW_MEMORY_COPY’ is not a member of ‘irr::video’
     bool flgcpy = driver->getTextureCreationFlag(video::ETCF_ALLOW_MEMORY_COPY);
                                                  ^
/home/ruehmann/minetest/src/cguittfont/CGUITTFont.h:130:36: error: ‘ETCF_ALLOW_MEMORY_COPY’ is not a member of ‘irr::video’
     driver->setTextureCreationFlag(video::ETCF_ALLOW_MEMORY_COPY, true);
                                    ^
/home/ruehmann/minetest/src/cguittfont/CGUITTFont.h:148:36: error: ‘ETCF_ALLOW_MEMORY_COPY’ is not a member of ‘irr::video’
     driver->setTextureCreationFlag(video::ETCF_ALLOW_MEMORY_COPY, flgcpy);
                                    ^
src/cguittfont/CMakeFiles/cguittfont.dir/build.make:62: die Regel für Ziel „src/cguittfont/CMakeFiles/cguittfont.dir/xCGUITTFont.cpp.o“ scheiterte
make[2]: *** [src/cguittfont/CMakeFiles/cguittfont.dir/xCGUITTFont.cpp.o] Fehler 1
CMakeFiles/Makefile2:553: die Regel für Ziel „src/cguittfont/CMakeFiles/cguittfont.dir/all“ scheiterte
```
Thanks,

**Comment by nerzhul** [comment]
seems related to irrlicht version

**Comment by sfan5** [comment]
caused by 084cdea6862cb65fe4bb807a211a9e1c17cffec8

**Comment by JPRuehmann** [comment]
I had Irlicht 1.9 and it had happen at the make in the cloned Directory.
I have downgraded to 1.8.4 and made a make clear, make and everything works fine again.
Thanks

**Comment by sfan5** [comment]
"I downgraded Irrlicht and now it works" is not the solution here.

Where did you install Irrlicht 1.9 from?

**Comment by JPRuehmann** [comment]
http://irrlicht.convextech.ca/

**Comment by sfan5** [comment]
`ERR_NAME_NOT_RESOLVED`

In any case: Irrlicht 1.9 is not officially released yet and it makes no sense for applications to support any svn revision that might come between 1.8.4 and the 1.9 release

**Comment by nerzhul** [comment]
I think we can close this issue as Irrlicht 1.9 is not released, we don't support unreleased version
