### ISSUE TITLE
Linker errors with IrrlichtMt automatically built alongside, using MSVC

### ISSUE THREAD

**Issue by OgelGames** [minetest/minetest#11402]
##### Minetest version

```
5.5.0-dev
```
Attempting to build from commit fa4dee0e62dcf2bbfb68b17cf97e438eab58be93

##### OS / Hardware

Operating system: Windows 10
CPU: Ryzen 5 3600

##### Summary
Building Minetest fails.

##### Steps to reproduce
* Clone `https://github.com/minetest/minetest`
* Clone `https://github.com/minetest/irrlicht` into `minetest/lib/irrlichtmt`
* Follow instructions for [compiling on windows](https://github.com/minetest/minetest#compiling-on-windows) (using vcpkg and CMake GUI)
* Build fails with the following errors:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'GL/glext.h': No such file or directory	IRRVIDEOOBJ	C:\Minetest\source\minetest\lib\irrlichtmt\source\Irrlicht\COpenGLCommon.h	20	
Error	C1083	Cannot open include file: 'GL/glext.h': No such file or directory	IRRVIDEOOBJ	C:\Minetest\source\minetest\lib\irrlichtmt\source\Irrlicht\COpenGLCommon.h	20	
Error	C1083	Cannot open include file: 'GL/glext.h': No such file or directory	IRRVIDEOOBJ	C:\Minetest\source\minetest\lib\irrlichtmt\source\Irrlicht\COpenGLCommon.h	20	
Error	C1083	Cannot open include file: 'GL/glext.h': No such file or directory	IRRVIDEOOBJ	C:\Minetest\source\minetest\lib\irrlichtmt\source\Irrlicht\COpenGLCommon.h	20	
Error	C1083	Cannot open include file: 'GL/glext.h': No such file or directory	IRRVIDEOOBJ	C:\Minetest\source\minetest\lib\irrlichtmt\source\Irrlicht\COpenGLCommon.h	20	
Error	C1083	Cannot open include file: 'GL/glext.h': No such file or directory	IRRVIDEOOBJ	C:\Minetest\source\minetest\lib\irrlichtmt\source\Irrlicht\COpenGLCommon.h	20	
Error	C1083	Cannot open include file: 'GL/glext.h': No such file or directory	IRRVIDEOOBJ	C:\Minetest\source\minetest\lib\irrlichtmt\source\Irrlicht\COpenGLCommon.h	20	
Error	C1083	Cannot open include file: 'GL/wglext.h': No such file or directory	IRRVIDEOOBJ	C:\Minetest\source\minetest\lib\irrlichtmt\source\Irrlicht\CWGLManager.cpp	12	
Error	LNK1181	cannot open input file 'C:\Minetest\source\build\lib\irrlichtmt\source\Irrlicht\IRRVIDEOOBJ.dir\Release\COpenGLCacheHandler.obj'	IrrlichtMt	C:\Minetest\source\build\lib\irrlichtmt\source\Irrlicht\LINK	1	
Error	LNK1181	cannot open input file '..\lib\Win32-VisualStudio\Release\IrrlichtMt.lib'	minetest	C:\Minetest\source\build\src\LINK	1	
```
* Use vcpkg to install missing files. (`vcpkg install opengl-registry --triplet x64-windows`)
* Build now fails with different errors:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1120	5 unresolved externals	minetest	C:\Minetest\source\minetest\bin\Release\minetest.exe	1	
Error	LNK2001	unresolved external symbol "__declspec(dllimport) class irr::video::SMaterial irr::video::IdentityMaterial" (__imp_?IdentityMaterial@video@irr@@3VSMaterial@12@A)	minetest	C:\Minetest\source\build\src\clientmap.obj	1	
Error	LNK2001	unresolved external symbol "__declspec(dllimport) unsigned int irr::video::MATERIAL_MAX_TEXTURES_USED" (__imp_?MATERIAL_MAX_TEXTURES_USED@video@irr@@3IA)	minetest	C:\Minetest\source\build\src\clientmap.obj	1	
Error	LNK2001	unresolved external symbol "__declspec(dllimport) class irr::core::CMatrix4<float> const irr::core::IdentityMatrix" (__imp_?IdentityMatrix@core@irr@@3V?$CMatrix4@M@12@B)	minetest	C:\Minetest\source\build\src\content_cao.obj	1	
Error	LNK2001	unresolved external symbol __imp_createDeviceEx	minetest	C:\Minetest\source\build\src\renderingengine.obj	1	
Error	LNK2001	unresolved external symbol __imp_createDevice	minetest	C:\Minetest\source\build\src\renderingengine.obj	1	
```

**Comment by SmallJoker** [comment]
Does the 5.4.1 build work?

**Comment by rubenwardy** [comment]
> Does the 5.4.1 build work? If so, please use git bisect to figure out the first bad commit (i.e. the one that caused it).

This is due to IrrlichtMt not finding OpenGL

**Comment by OgelGames** [comment]
Yes, 5.4.1 builds perfectly without any errors. (using Irrlicht from vcpkg)

Not sure if I'll be able to find the commit, as I haven't built Minetest since Irrlicht was forked, because I had problems building IrrlichtMt.

 IrrlichtMt does build successfully on the current commit though, once the missing files are added, so I might be able to try.

**Comment by LoneWolfHT** [comment]
Sounds like the issue I was having with my actions PR https://github.com/minetest/minetest/pull/11176#issuecomment-845156947

**Comment by sfan5** [comment]
You're missing half the story here, the include errors can be resolved by installing `opengl-registry` (I didn't know this either, very useful). OP has done this and is now getting linker errors which look like as if IrrlichtMt is not being linked at all.

I'll try this later in my dev VM to see if I can reproduce it.

**Comment by sfan5** [comment]
I immediately spot a problem, IrrlichtMt does not detect any drivers from its own headers:
![grafik](https://user-images.githubusercontent.com/1042418/124014143-6fb70100-d9e3-11eb-88fb-57debedfba93.png)
This is caused by a path being set wrong inside IrrlichtMt.

With that fixed, I do get the same linking errors as described on the OP post.

**Comment by sfan5** [comment]
Okay the actual reason here is pretty simple, IrrlichtMt headers assume the wrong calling convention for static builds.
![grafik](https://user-images.githubusercontent.com/1042418/124017107-9f1b3d00-d9e6-11eb-8044-1ddbfb9ff0b6.png)

I doubt this ever worked before, not sure whats the best way to make it work.

**Comment by sfan5** [comment]
Will be fixed by minetest/irrlicht@22c3219 in combination with #11287

**Comment by OgelGames** [comment]
I can confirm that it is fixed, I did have to re-clone minetest and IrrlichtMt, but I was able to build it successfully after that.
