### ISSUE TITLE
s_base.cpp compile error with -std=c++11

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#3512]
jni/../jni/src/script/cpp_api/s_base.cpp: In constructor 'ScriptApiBase::ScriptApiBase()':
jni/../jni/src/script/cpp_api/s_base.cpp:71:22: error: no matching function for call to 'std::mutex::mutex(bool)'
  m_luastackmutex(true)
                      ^
In file included from jni/src/threading/mutex.h:31:0,
                 from jni/src/threads.h:41,
                 from jni/src/script/cpp_api/s_base.h:31,
                 from jni/../jni/src/script/cpp_api/s_base.cpp:20:
/home/server/crystax/sources/cxx-stl/gnu-libstdc++/5/include/mutex:126:5: note: candidate: constexpr std::mutex::mutex()
     mutex() noexcept = default;
     ^
/home/server/crystax/sources/cxx-stl/gnu-libstdc++/5/include/mutex:126:5: note:   candidate expects 0 arguments, 1 provided
[armeabi-v7a] Compile++ thumb: minetest <= s_node.cpp
make[2]: [obj/local/armeabi-v7a/objs/minetest/jni/src/script/cpp_api/s_base.o] Error 1

**Comment by est31** [comment]
This seems like its caused by 52e5b513 .

Most likely "normal" c++11 mode is broken as well, I'm not sure, at least I can't find any docs of the method with one param: http://en.cppreference.com/w/cpp/thread/recursive_mutex

**Comment by est31** [comment]
Err, that's the class we should use if the param is true.

This is the docs for std::mutex of course:
http://de.cppreference.com/w/cpp/thread/mutex

**Comment by est31** [comment]
I confirm, 52e5b513ed9dc143c967c733423fe751e1b663d1 broke normal compilation with c++11 as well.

**Comment by est31** [comment]
Added blocker label, we can't release something that can't be built with c++11, and the bug is nicely reproducible and can be fixed quite easily.

**Comment by est31** [comment]
@kwolekr do you want to fix it?

**Comment by est31** [comment]
Fixed by e50c784e2ca55735fc360ae51534288c2ea59ca5
