### ISSUE TITLE
Linking Minetest-Server against PostgreSQL fails on Ubuntu 18.04 Server

### ISSUE THREAD

**Issue by debagos** [minetest/minetest#12149]
#### Minetest version
```
Release 5.5.0 till current master (didn't test older versions)
```

#### OS / Hardware
Operating system: Ubuntu 18.04 Server

#### Summary
When you try to build a server-only build with Minetest 5.5.0 from source with PostgreSQL enabled on a 18.04 Ubuntu server the linking against PostgreSQL after compilation fails. The linker can't find the PG definitions, even when you specify "PostgreSQL_INCLUDE_DIR" and "PostgreSQL_LIBRARY". Doesn't matter the PG version, tested 10, 12 and 14 repo version as well as self compiled.

#### Console output
```
[100%] Linking CXX executable ../bin/minetestserver
CMakeFiles/minetestserver.dir/database/database-postgresql.cpp.o: In Funktion »Database_PostgreSQL::initialized() const«:
database-postgresql.cpp:(.text+0x69): Warnung: undefinierter Verweis auf »PQstatus«
CMakeFiles/minetestserver.dir/database/database-postgresql.cpp.o: In Funktion »Database_PostgreSQL::~Database_PostgreSQL()«:
database-postgresql.cpp:(.text+0x407): Warnung: undefinierter Verweis auf »PQfinish«
CMakeFiles/minetestserver.dir/database/database-postgresql.cpp.o: In Funktion »Database_PostgreSQL::connectToDatabase()«:
database-postgresql.cpp:(.text+0x452): Warnung: undefinierter Verweis auf »PQconnectdb«
database-postgresql.cpp:(.text+0x45e): Warnung: undefinierter Verweis auf »PQstatus«
```
and so on...
( "Warnung: undefinierter Verweis auf" is German and translates to "Warning: undefined reference to" )

#### Cause
Discord user paradust#7677 helped me (thank you man! all credit goes to you) and identified the problem. He said CMake isn't including "libpq.so" on the command line. That is because of a typo in the "CMakeLists.txt" file. In line 554 and 607 it should be "PostgreSQL_LIBRARY", but there is written "PostgreSQL_LIBRARIES".

#### Fix
Replace "PostgreSQL_LIBRARIES" with "PostgreSQL_LIBRARY" in the "CMakeLists.txt" file on line 554 and 607.

**Comment by sfan5** [comment]
> That is because of a typo in the "CMakeLists.txt" file. In line 554 and 607 it should be "PostgreSQL_LIBRARY", but there is written "PostgreSQL_LIBRARIES".

This is not a typo, the variable is named like this in the find script:
https://github.com/Kitware/CMake/blob/80bcbe2d85232d748e31fb4de1016af60788505d/Modules/FindPostgreSQL.cmake#L55-L59

What _could_ help is this but I don't know if this is actually correct on a whim:
```diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 1d6177ba3..2962b5de2 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -136,6 +136,7 @@ if(ENABLE_POSTGRESQL)
                if(PostgreSQL_INCLUDE_DIR AND PostgreSQL_LIBRARY)
                        set(PostgreSQL_FOUND TRUE)
                        set(PostgreSQL_INCLUDE_DIRS ${PostgreSQL_INCLUDE_DIR})
+                       set(PostgreSQL_LIBRARIES ${PostgreSQL_LIBRARY})
                endif()
        else()
                find_package(PostgreSQL)
```

**Comment by Beanzilla** [comment]
Confirmed for Minetest 5.5.1 on Xubuntu 20.04.04 LTS

Just changed the PostgreSQL_LIBRARIES to PostgeSQL_LIBRARY and it compiled.
