### PR TITLE
Fix MSVC error caused by ed10005

### PR DESCRIPTION
**Pull request by SmallJoker**
Fixes following error:
> minetest\src\mapgen.cpp(521): error C3861: "strcasecmp": Identifier was not found.

### CODE REVIEW

**Comment by nerzhul** [comment]
instead of including porting maybe include the right header could be good.

**Comment by nerzhul** [comment]
@Zeno- what do you think ?

**Comment by Zeno-** [comment]
@nerzhul umm. porting.h is the correct header to include

**Comment by nerzhul** [comment]
Then okay

**Comment by Zeno-** [comment]
The comment after the #include might be misleading though... I'd have just left it out.

**Comment by Zeno-** [comment]
58d62ad04556de37f7870048f0f07aaa3ee0cd13
