### ISSUE TITLE
‘m_thread_handle’ was not declared in this scope

### ISSUE THREAD

**Issue by kahrl** [minetest/minetest#4054]
I currently can't build minetest, build fails with the following errors and warnings (introduced by 46fd114e9a4e05b74576dce682e24357363298e7?). I build with ``-std=c++11``.
```
[  0%] Built target cguittfont
[  1%] Built target jsoncpp
-- *** Detected Git version 0.4.13-dev-4a93080 ***
[  1%] Built target GenerateVersion
[  2%] Building CXX object src/CMakeFiles/minetest.dir/threading/thread.cpp.o
/home/kahrl/minetest/src/threading/thread.cpp: In member function ‘bool Thread::kill()’:
/home/kahrl/minetest/src/threading/thread.cpp:210:17: error: ‘m_thread_handle’ was not declared in this scope
  pthread_cancel(m_thread_handle);
                 ^
/home/kahrl/minetest/src/threading/thread.cpp: In member function ‘bool Thread::bindToProcessor(unsigned int)’:
/home/kahrl/minetest/src/threading/thread.cpp:373:32: error: ‘m_thread_handle’ was not declared in this scope
  return pthread_setaffinity_np(m_thread_handle, sizeof(cpuset), &cpuset) == 0;
                                ^
/home/kahrl/minetest/src/threading/thread.cpp: In member function ‘bool Thread::setPriority(int)’:
/home/kahrl/minetest/src/threading/thread.cpp:419:28: error: ‘m_thread_handle’ was not declared in this scope
  if (pthread_getschedparam(m_thread_handle, &policy, &sparam) != 0)
                            ^
/home/kahrl/minetest/src/threading/thread.cpp:426:31: error: ‘m_thread_handle’ was not declared in this scope
  return pthread_setschedparam(m_thread_handle, policy, &sparam) == 0;
                               ^
/home/kahrl/minetest/src/threading/thread.cpp: In member function ‘bool Thread::bindToProcessor(unsigned int)’:
/home/kahrl/minetest/src/threading/thread.cpp:405:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
/home/kahrl/minetest/src/threading/thread.cpp: In member function ‘bool Thread::setPriority(int)’:
/home/kahrl/minetest/src/threading/thread.cpp:429:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
src/CMakeFiles/minetest.dir/build.make:1214: recipe for target 'src/CMakeFiles/minetest.dir/threading/thread.cpp.o' failed
make[2]: *** [src/CMakeFiles/minetest.dir/threading/thread.cpp.o] Error 1
CMakeFiles/Makefile2:177: recipe for target 'src/CMakeFiles/minetest.dir/all' failed
make[1]: *** [src/CMakeFiles/minetest.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by est31** [comment]
We shouldn't release minetest with a build bug for c++11 compilers. People in the future want to build minetest too, and perhaps they want to try it how it was in the days of 0.4.14.

**Comment by Zeno-** [comment]
Possibly

```
@@ -155,15 +155,15 @@ class Thread {
 	bool m_joinable;
 	Atomic<bool> m_request_stop;
 	Atomic<bool> m_running;
 	Mutex m_mutex;
 
-#if !USE_CPP11_THREADS
+#if !defined USE_CPP11_THREADS
 	threadhandle_t m_thread_handle;
-#if _WIN32
-	threadid_t m_thread_id;
-#endif
+#   if _WIN32
+        threadid_t m_thread_id;
+#   endif
 #endif
 
 	static ThreadStartFunc threadProc;
 
 #ifdef _AIX
```

**Comment by Zeno-** [comment]
Fixed preprocessor in commit: e77cc8f

I'll leave this open until kahrl confirms it fixes the build error

**Comment by kahrl** [comment]
@Zeno- I'm still getting the same errors, unfortunately.

**Comment by Zeno-** [comment]
@kahrl I just looked and you're right. It's almost as if thread.cpp was committed without being finished :/

**Comment by Zeno-** [comment]
@ShadowNinja 46fd114

**Comment by ShadowNinja** [comment]
This should fix it http://ix.io/yum/diff

**Comment by ShadowNinja** [comment]
a53357d2917d57966503348e7c030c024e89bb1b
