### PR TITLE
Fix some Game members not being freed after some startup errors (regression)

### PR DESCRIPTION
**Pull request by grorp**
This PR fixes a regression from fd8e02195ea1c44f93a18f18e1e850c71ff0d33b. In that commit, I moved some freeing from `Game::~Game` to `Game::shutdown`. Now I realize that `Game::shutdown` isn't called in all cases, for example when a shader compilation error occurs.

Behavior in case of a shader compilation error:

| Version                                                       | Behavior                                                                                                                         |
| ------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------- |
| master with fd8e02195ea1c44f93a18f18e1e850c71ff0d33b reverted | Loading screen freezes for 5 seconds in "Initializing nodes..." phase while server shuts down. Shader error is shown afterwards. |
| master                                                        | Shader error is shown immediately. Server is not shut down and can be joined using a second client.                              |
| this PR                                                            | "Shutting down..." screen is shown for 5 seconds without freezing while server shuts down. Shader error is shown afterwards.      |

This PR works by always calling `Game::shutdown`. Somewhat related old PR: #9742

## To do

This PR is a Ready for Review.

Notes:

 - I think the stuff I moved from `Game::~Game` to `Game::shutdown` could actually be moved back. However, that would mean spawning a thread (StopThread) and rendering the shutdown screen in a destructor, which feels bad. What if one of these things throws an exception? Would this be a better solution?

 - Could always calling `Game::shutdown` introduce new bugs?

## How to test

Edit shaders to make shader compilation fail. Add this code to `builtin/game/init.lua`:

```lua
minetest.register_on_shutdown(function()
	print("wa wa wa waiting")
	local t = os.time() + 5
	while os.time() < t do
	end
	print("finished waiting")
end)
```

Verify that the behavior of different versions matches what I describe in the table above.

### CODE REVIEW

**Comment by sfan5** [comment]
I think a C++-y approach would be if `~Game()` contained code to destroy all members.
`shutdown()` is just then the normal way to deinit the client, but in exceptional circumstances still nothing would leak.

**Comment by grorp** [comment]
When I first implemented your suggestion, it unfortunately made things worse: When a shader error occured, the loading screen froze again during server shutdown. To fix this, I moved some exception catching down from `ClientLauncher` to `Game`. I hope this doesn't have unexpected side effects...

**Review by sfan5 — APPROVED** [review]
Looks good.
