### ISSUE TITLE
Interlaced 3D mode does not work

### ISSUE THREAD

**Issue by srifqi** [minetest/minetest#10998]
##### Minetest version
```
5.4.0
```

##### OS / Hardware
Operating system: Windows 10 (10.0.18363)
CPU: AMD Ryzen 5 4500U with Radeon Graphics

GPU model: AMD Radeon(TM) Graphics
OpenGL version: 4.6.13596

##### Summary
Interlaced 3D mode does not work. GLSL vertex shader failed to compile.

By using `git bisect`, I found that this issue was introduced in #10506 (commit 707c8c1e95d8db2d84909e7957b4dc9138e05599).

<details>
<summary>Error log</summary>

```
ERROR[Main]: Irrlicht: GLSL shader failed to compile
ERROR[Main]: Irrlicht: Vertex shader failed to compile with the following errors:
ERROR: 0:61: error(#160) Cannot convert from: "in 4-component vector of vec4" to: "default out highp 2-component vector of vec2"
ERROR: error(#273) 1 compilation errors.  No code generated


ERROR[Main]: generate_shader(): failed to generate "3d_interlaced_merge", addHighLevelShaderMaterial failed.
WARNING[Main]: Vertex shader program:
WARNING[Main]: ----------------------------------
WARNING[Main]: 1: 
WARNING[Main]: 2: 			#version 120
WARNING[Main]: 3: 			#define lowp
WARNING[Main]: 4: 			#define mediump
WARNING[Main]: 5: 			#define highp
WARNING[Main]: 6: 			#define NDT_NORMAL 0
WARNING[Main]: 7: #define NDT_AIRLIKE 1
WARNING[Main]: 8: #define NDT_LIQUID 2
WARNING[Main]: 9: #define NDT_FLOWINGLIQUID 3
WARNING[Main]: 10: #define NDT_GLASSLIKE 4
WARNING[Main]: 11: #define NDT_ALLFACES 5
WARNING[Main]: 12: #define NDT_ALLFACES_OPTIONAL 6
WARNING[Main]: 13: #define NDT_TORCHLIKE 7
WARNING[Main]: 14: #define NDT_SIGNLIKE 8
WARNING[Main]: 15: #define NDT_PLANTLIKE 9
WARNING[Main]: 16: #define NDT_FENCELIKE 10
WARNING[Main]: 17: #define NDT_RAILLIKE 11
WARNING[Main]: 18: #define NDT_NODEBOX 12
WARNING[Main]: 19: #define NDT_GLASSLIKE_FRAMED 13
WARNING[Main]: 20: #define NDT_FIRELIKE 14
WARNING[Main]: 21: #define NDT_GLASSLIKE_FRAMED_OPTIONAL 15
WARNING[Main]: 22: #define NDT_PLANTLIKE_ROOTED 17
WARNING[Main]: 23: #define TILE_MATERIAL_BASIC 0
WARNING[Main]: 24: #define TILE_MATERIAL_ALPHA 1
WARNING[Main]: 25: #define TILE_MATERIAL_LIQUID_TRANSPARENT 2
WARNING[Main]: 26: #define TILE_MATERIAL_LIQUID_OPAQUE 3
WARNING[Main]: 27: #define TILE_MATERIAL_WAVING_LEAVES 4
WARNING[Main]: 28: #define TILE_MATERIAL_WAVING_PLANTS 5
WARNING[Main]: 29: #define TILE_MATERIAL_OPAQUE 6
WARNING[Main]: 30: #define TILE_MATERIAL_WAVING_LIQUID_BASIC 7
WARNING[Main]: 31: #define TILE_MATERIAL_WAVING_LIQUID_TRANSPARENT 8
WARNING[Main]: 32: #define TILE_MATERIAL_WAVING_LIQUID_OPAQUE 9
WARNING[Main]: 33: #define TILE_MATERIAL_PLAIN 10
WARNING[Main]: 34: #define TILE_MATERIAL_PLAIN_ALPHA 11
WARNING[Main]: 35: #define MATERIAL_TYPE 0
WARNING[Main]: 36: #define DRAW_TYPE 0
WARNING[Main]: 37: #define ENABLE_WAVING_WATER 1
WARNING[Main]: 38: #define WATER_WAVE_HEIGHT 1.00000
WARNING[Main]: 39: #define WATER_WAVE_LENGTH 20.0000
WARNING[Main]: 40: #define WATER_WAVE_SPEED 5.00000
WARNING[Main]: 41: #define ENABLE_WAVING_LEAVES 1
WARNING[Main]: 42: #define ENABLE_WAVING_PLANTS 1
WARNING[Main]: 43: #define ENABLE_TONE_MAPPING 0
WARNING[Main]: 44: #define FOG_START 0.400000
WARNING[Main]: 45: 
WARNING[Main]: 46: 			#define mWorldView gl_ModelViewMatrix
WARNING[Main]: 47: 			#define mWorldViewProj gl_ModelViewProjectionMatrix
WARNING[Main]: 48: 			#define mTexture (gl_TextureMatrix[0])
WARNING[Main]: 49: 			#define mNormal gl_NormalMatrix
WARNING[Main]: 50: 
WARNING[Main]: 51: 			#define inVertexPosition gl_Vertex
WARNING[Main]: 52: 			#define inVertexColor gl_Color
WARNING[Main]: 53: 			#define inTexCoord0 gl_MultiTexCoord0
WARNING[Main]: 54: 			#define inVertexNormal gl_Normal
WARNING[Main]: 55: 			#define inVertexTangent gl_MultiTexCoord1
WARNING[Main]: 56: 			#define inVertexBinormal gl_MultiTexCoord2
WARNING[Main]: 57: 			varying mediump vec2 varTexCoord;
WARNING[Main]: 58: 
WARNING[Main]: 59: void main(void)
WARNING[Main]: 60: {
WARNING[Main]: 61: 	varTexCoord = inTexCoord0;
WARNING[Main]: 62: 	gl_Position = inVertexPosition;
WARNING[Main]: 63: }
WARNING[Main]: 64: 
WARNING[Main]: End of Vertex shader program.
WARNING[Main]:  
WARNING[Main]: Fragment shader program:
WARNING[Main]: ----------------------------------
WARNING[Main]: 1: 
WARNING[Main]: 2: 			#version 120
WARNING[Main]: 3: 			#define lowp
WARNING[Main]: 4: 			#define mediump
WARNING[Main]: 5: 			#define highp
WARNING[Main]: 6: 			#define NDT_NORMAL 0
WARNING[Main]: 7: #define NDT_AIRLIKE 1
WARNING[Main]: 8: #define NDT_LIQUID 2
WARNING[Main]: 9: #define NDT_FLOWINGLIQUID 3
WARNING[Main]: 10: #define NDT_GLASSLIKE 4
WARNING[Main]: 11: #define NDT_ALLFACES 5
WARNING[Main]: 12: #define NDT_ALLFACES_OPTIONAL 6
WARNING[Main]: 13: #define NDT_TORCHLIKE 7
WARNING[Main]: 14: #define NDT_SIGNLIKE 8
WARNING[Main]: 15: #define NDT_PLANTLIKE 9
WARNING[Main]: 16: #define NDT_FENCELIKE 10
WARNING[Main]: 17: #define NDT_RAILLIKE 11
WARNING[Main]: 18: #define NDT_NODEBOX 12
WARNING[Main]: 19: #define NDT_GLASSLIKE_FRAMED 13
WARNING[Main]: 20: #define NDT_FIRELIKE 14
WARNING[Main]: 21: #define NDT_GLASSLIKE_FRAMED_OPTIONAL 15
WARNING[Main]: 22: #define NDT_PLANTLIKE_ROOTED 17
WARNING[Main]: 23: #define TILE_MATERIAL_BASIC 0
WARNING[Main]: 24: #define TILE_MATERIAL_ALPHA 1
WARNING[Main]: 25: #define TILE_MATERIAL_LIQUID_TRANSPARENT 2
WARNING[Main]: 26: #define TILE_MATERIAL_LIQUID_OPAQUE 3
WARNING[Main]: 27: #define TILE_MATERIAL_WAVING_LEAVES 4
WARNING[Main]: 28: #define TILE_MATERIAL_WAVING_PLANTS 5
WARNING[Main]: 29: #define TILE_MATERIAL_OPAQUE 6
WARNING[Main]: 30: #define TILE_MATERIAL_WAVING_LIQUID_BASIC 7
WARNING[Main]: 31: #define TILE_MATERIAL_WAVING_LIQUID_TRANSPARENT 8
WARNING[Main]: 32: #define TILE_MATERIAL_WAVING_LIQUID_OPAQUE 9
WARNING[Main]: 33: #define TILE_MATERIAL_PLAIN 10
WARNING[Main]: 34: #define TILE_MATERIAL_PLAIN_ALPHA 11
WARNING[Main]: 35: #define MATERIAL_TYPE 0
WARNING[Main]: 36: #define DRAW_TYPE 0
WARNING[Main]: 37: #define ENABLE_WAVING_WATER 1
WARNING[Main]: 38: #define WATER_WAVE_HEIGHT 1.00000
WARNING[Main]: 39: #define WATER_WAVE_LENGTH 20.0000
WARNING[Main]: 40: #define WATER_WAVE_SPEED 5.00000
WARNING[Main]: 41: #define ENABLE_WAVING_LEAVES 1
WARNING[Main]: 42: #define ENABLE_WAVING_PLANTS 1
WARNING[Main]: 43: #define ENABLE_TONE_MAPPING 0
WARNING[Main]: 44: #define FOG_START 0.400000
WARNING[Main]: 45: uniform sampler2D baseTexture;
WARNING[Main]: 46: uniform sampler2D normalTexture;
WARNING[Main]: 47: uniform sampler2D textureFlags;
WARNING[Main]: 48: 
WARNING[Main]: 49: #define leftImage baseTexture
WARNING[Main]: 50: #define rightImage normalTexture
WARNING[Main]: 51: #define maskImage textureFlags
WARNING[Main]: 52: 
WARNING[Main]: 53: varying mediump vec2 varTexCoord;
WARNING[Main]: 54: 
WARNING[Main]: 55: void main(void)
WARNING[Main]: 56: {
WARNING[Main]: 57: 	vec2 uv = varTexCoord.st;
WARNING[Main]: 58: 	vec4 left = texture2D(leftImage, uv).rgba;
WARNING[Main]: 59: 	vec4 right = texture2D(rightImage, uv).rgba;
WARNING[Main]: 60: 	vec4 mask = texture2D(maskImage, uv).rgba;
WARNING[Main]: 61: 	vec4 color;
WARNING[Main]: 62: 	if (mask.r > 0.5)
WARNING[Main]: 63: 		color = right;
WARNING[Main]: 64: 	else
WARNING[Main]: 65: 		color = left;
WARNING[Main]: 66: 	gl_FragColor = color;
WARNING[Main]: 67: }
WARNING[Main]: 68: 
WARNING[Main]: End of Fragment shader program.
WARNING[Main]:  
WARNING[Main]: Geometry shader program:
WARNING[Main]: ----------------------------------
WARNING[Main]: 1: 
WARNING[Main]: End of Geometry shader program.
WARNING[Main]:  
```
</details>

##### Steps to reproduce
Use `3d_mode = interlaced` and play a world.

**Comment by srifqi** [comment]
Possible fix:
```diff
diff --git a/client/shaders/3d_interlaced_merge/opengl_fragment.glsl b/client/shaders/3d_interlaced_merge/opengl_fragment.glsl
index 7cba61b39..6d3ae5093 100644
--- a/client/shaders/3d_interlaced_merge/opengl_fragment.glsl
+++ b/client/shaders/3d_interlaced_merge/opengl_fragment.glsl
@@ -6,7 +6,7 @@ uniform sampler2D textureFlags;
 #define rightImage normalTexture
 #define maskImage textureFlags
 
-varying mediump vec2 varTexCoord;
+varying mediump vec4 varTexCoord;
 
 void main(void)
 {
diff --git a/client/shaders/3d_interlaced_merge/opengl_vertex.glsl b/client/shaders/3d_interlaced_merge/opengl_vertex.glsl
index 860049481..224b7d183 100644
--- a/client/shaders/3d_interlaced_merge/opengl_vertex.glsl
+++ b/client/shaders/3d_interlaced_merge/opengl_vertex.glsl
@@ -1,4 +1,4 @@
-varying mediump vec2 varTexCoord;
+varying mediump vec4 varTexCoord;
 
 void main(void)
 {
```
