### ISSUE TITLE
Windows build fails with MinGW 32-bit

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#3151]
```
[ 41%] Building CXX object src/CMakeFiles/minetest.dir/threading/semaphore.cpp.obj
/home/stefan/mt-build/build/minetest/minetest/src/threading/semaphore.cpp: In constructor ‘Semaphore::Semaphore(int)’:
/home/stefan/mt-build/build/minetest/minetest/src/threading/semaphore.cpp:29:30: error: ‘LONG_MAX’ was not declared in this scope
  #define MAX_SEMAPHORE_COUNT LONG_MAX - 1
                              ^
/home/stefan/mt-build/build/minetest/minetest/src/threading/semaphore.cpp:58:41: note: in expansion of macro ‘MAX_SEMAPHORE_COUNT’
  semaphore = CreateSemaphore(NULL, val, MAX_SEMAPHORE_COUNT, NULL);
                                         ^
src/CMakeFiles/minetest.dir/build.make:1192: die Regel für Ziel „src/CMakeFiles/minetest.dir/threading/semaphore.cpp.obj“ scheiterte
make[2]: *** [src/CMakeFiles/minetest.dir/threading/semaphore.cpp.obj] Fehler 1

```

**Comment by est31** [comment]
Likely caused by #2613

**Comment by ShadowNinja** [comment]
Adding a `<climits>` include might fix this.

**Comment by ShadowNinja** [comment]
@sfan5: Any success with my suggestion?

**Comment by kaeza** [comment]
Adding `#include <climits>` does fix the issue.

**Comment by ShadowNinja** [comment]
20405edb06f44308aae760dc2f4dad5c61e0d30f
