### ISSUE TITLE
Does not build with Irrlicht 1.9 (svn) and Freetype enabled

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#1166]
<pre>home/stefan/minetest/src/guiTextInputMenu.cpp:117:33: error: allocating an
      object of abstract class type 'gui::intlGUIEditBox'
  ...e = (gui::IGUIElement *) new gui::intlGUIEditBox(text.c_str(), true,...
                                  ^
/tmp/trunk/include/IGUIEditBox.h:73:16: note: unimplemented pure virtual method
      'isDrawBackgroundEnabled' in 'intlGUIEditBox'
                virtual bool isDrawBackgroundEnabled() const = 0;
                             ^
/tmp/trunk/include/IGUIEditBox.h:81:16: note: unimplemented pure virtual method
      'isDrawBorderEnabled' in 'intlGUIEditBox'
                virtual bool isDrawBorderEnabled() const = 0;
                             ^
/tmp/trunk/include/IGUIEditBox.h:139:16: note: unimplemented pure virtual method
      'setCursorChar' in 'intlGUIEditBox'
                virtual void setCursorChar(const wchar_t cursorChar) = 0;
                             ^
/tmp/trunk/include/IGUIEditBox.h:142:19: note: unimplemented pure virtual method
      'getCursorChar' in 'intlGUIEditBox'
                virtual wchar_t getCursorChar() const = 0;
                                ^
/tmp/trunk/include/IGUIEditBox.h:146:16: note: unimplemented pure virtual method
      'setCursorBlinkTime' in 'intlGUIEditBox'
                virtual void setCursorBlinkTime(irr::u32 timeMs) = 0;
                             ^
/tmp/trunk/include/IGUIEditBox.h:149:20: note: unimplemented pure virtual method
      'getCursorBlinkTime' in 'intlGUIEditBox'
                virtual irr::u32 getCursorBlinkTime() const = 0;
                                 ^
1 error generated.
</pre>
