### ISSUE TITLE
[0.4.10] Does not compile under C++11 standard - expected unqualified-id before ‘char’

### ISSUE THREAD

**Issue by Talkless** [minetest/minetest#1702]
In Kubuntu 14.04.1 amd64, GCC 4.8.2 I get:
```
In file included from /home/vincas/code/opensource/minetest-0.4.10/src/game.cpp:45:0:
/usr/include/libintl.h:39:14: error: expected unqualified-id before ‘char’
 extern char *gettext (const char *__msgid)
              ^
/usr/include/libintl.h:39:14: error: expected initializer before ‘char’
```

Also, lot's of warnings like these:
```
home/vincas/code/opensource/minetest-0.4.10/src/cmake_config.h:29:26: warning: invalid suffix on  iteral; C++11 requires a space between lieral and identifier [-Wliteral-suffix] #define CMAKE_BUILD_INFO "BUILD_TYPE="CMAKE_BUILD_TYPE" RUN_IN_PLACE=1 USE_GETTEXT=0 USE_SOUND=1 USE_CURL=1 USE_FREETYPE=1 USE_LUAJIT=1 STATIC_SHAREDIR=."
```
I guess it's referring to [user defined literals](https://en.wikipedia.org/wiki/C%2B%2B11#User-defined_literals)?

This is my configure script:
```
#!/usr/bin/env bash
CXXFLAGS="-march=native -O3 -std=c++11 -g" cmake \
-DCMAKE_BUILD_TYPE=Release \
-DIRRLICHT_SOURCE_DIR=/home/vincas/code/opensource/irrlicht-1.8.1 \
-DUSE_LUAJIT=1 \
-DRUN_IN_PLACE=1 \
-DENABLE_FREETYPE=1 \
.
```

**Comment by nerzhul** [comment]
I tested the build with C++11 on GCC 4.9.2 and CLang 3.5/3.6 it works like a charm. minetest will not use C++11 at this moment.
